"""add_save_column_to_news_analysis

Revision ID: 5e6c88a2887e
Revises: 6fb5cee241cd
Create Date: 2025-09-20 19:15:03.799042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6c88a2887e'
down_revision: Union[str, Sequence[str], None] = '6fb5cee241cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_analysis', sa.Column('save', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_analysis', 'save')
    # ### end Alembic commands ###
